### 로그인 (JWT 발급)
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "master",
  "password": "Password1!"
}
> {%
  let authHeader = response.headers.valueOf("Authorization");
  if (authHeader) {
    client.global.set("access_token", authHeader);
  } else {
    throw new Error("Authorization 헤더가 응답에 존재하지 않음");
  }
%}

### 허브 매니저 생성 전 관리자 권한으로 허브가 만들어져야 합니다.
POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}
#X-User-Id: 123
#X-User-Role: MASTER_ADMIN

{
  "hubName": "테스트 데이터",
  "locationApi": {
    "address": "테스트 주소",
    "latitude": 37.514219,
    "longitude": 127.112628
  }
}
> {%
  client.global.set("hubId", response.body.hubId)
%}


### 4. 허브 매니저 회원가입 (관리자 권한으로 허브가 만들어져 있어야 합니다.)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "hubmanage",
  "slackEmail": "testuser7@email.com",
  "password": "Password1!",
  "role": "HUB_MANAGER",
  "hubFeignResponse": {
  "hubId": "{{hubId}}",
  "hubName": "서울특별시 센터",
  "address": "서울특별시 송파구 송파대로 55",
  "latitude": 37.514219,
  "longitude": 127.112628
}
}

### 사용자 검증 (비밀번호 확인 및 userId, username, role 반환)
POST {{baseUrl}}/api/v1/app/users/validate
Content-Type: application/json

{
  "username": "hubmanage",
  "password": "Password1!"
}
> {%
  if (response.body.userId) {
    client.global.set("user_id", response.body.userId.toString());
  } else {
    throw new Error("userId가 응답에 존재하지 않음");
  }
  client.global.set("username", response.body.username);
  client.global.set("role", response.body.role);
%}

### 로그인 (JWT 발급)
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "hubmanage",
  "password": "Password1!"
}
> {%
  let authHeader = response.headers.valueOf("Authorization");
  if (authHeader) {
    client.global.set("access_token", authHeader);
  } else {
    throw new Error("Authorization 헤더가 응답에 존재하지 않음");
  }
%}