services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    networks:
      - app_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  zipkin:
    container_name: zipkin11
    image: openzipkin/zipkin
    networks:
      - app_network
    ports:
      - "9411:9411"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"   # 레디스 기본 포트
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
