services:
  # 인프라

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sa" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - app_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  zipkin:
    container_name: zipkin11
    image: openzipkin/zipkin
    networks:
      - app_network
    ports:
      - "9411:9411"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - app_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"  # Prometheus 기본 포트
    networks:
      - app_network
    volumes:
      - ./server/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml  # prometheus.yml 파일 경로 수정
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"  # Grafana 기본 포트
    networks:
      - app_network
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'  # Grafana 관리자 비밀번호
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana  # Grafana 데이터 저장소

  # MSA 모듈
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    ports:
      - "18999:18999"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:18999" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 55
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      zipkin:
        condition: service_started
      grafana:
        condition: service_started
      prometheus:
        condition: service_started
    env_file:
      - .env

  config:
    build:
      context: .
      dockerfile: config/Dockerfile
    container_name: config
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "8888:8888"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "19000:19000"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:19000/actuator/health" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    env_file:
      - .env

  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: user
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "19021:19021"
    networks:
      - app_network
    env_file:
      - .env

  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth
    depends_on:
      - user
    ports:
      - "19022:19022"
    networks:
      - app_network
    env_file:
      - .env

  product:
    build:
      context: .
      dockerfile: product/Dockerfile
    container_name: product
    depends_on:
      - user
    ports:
      - "19001:19001"
    networks:
      - app_network
    env_file:
      - .env


networks:
  app_network:
    driver: bridge

volumes:
  grafana-storage:
