### 환경 변수 설정
@host = http://localhost:19011
@contentType = application/json

## Company 서비스
### 1. 업체가 속한 허브 조회
GET http://localhost:19030/api/v1/companies/{{companyId}}
Content-Type: {{contentType}}

## Delivery 서비스
### 1. 배송 담당자의 담당 배송 모두 조회
GET http://localhost:19014/api/v1/app/deliveries?{{userId}}
Content-Type: {{contentType}}


### 2. 배송 생성 요청
POST http://localhost:19014/api/v1/app/deliveries
Content-Type: {{contentType}}

{
  "orderId": "550e8400-e29b-41d4-a716-446655440001",
  "customerId": "550e8400-e29b-41d4-a716-446655440003",
  "fromHubId": "550e8400-e29b-41d4-a716-446655440001",
  "toHubId": "550e8400-e29b-41d4-a716-446655440001"
}

### 3. 배송 삭제
DELETE http://localhost:19014/api/v1/app/deliveries/{{deliveryId}}
Content-Type: {{contentType}}

## DeliveryRoute 서비스
### 1. 배송 경로 생성
POST http://localhost:19014/api/v1/app/deliveryRoutes
Content-Type: {{contentType}}

{
  "deliveryId": "550e8400-e29b-41d4-a716-446655440001",
  "departureHubId": "550e8400-e29b-41d4-a716-446655440003",
  "destinationHubId": "550e8400-e29b-41d4-a716-446655440001",
}

### 2. 배송 담당자에게 할당된 배송 경로 모두 조회
GET http://localhost:19014/api/v1/app/deliveryRoutes?{{deliveryManagerId}}
Content-Type: {{contentType}

### 3. 배송 경로 삭제
POST http://localhost:19014/api/v1/app/deliveryRoutes/{{deliveryId}}}
Content-Type: {{contentType}}


## Stock 서비스
### 1. 재고 준비 요청
POST http://localhost:19001/api/v1/app/stock/prepare
Content-Type: {{contentType}}

{
  "stocks": [
    {
      "stockId": {
        "productId": "550e8400-e29b-41d4-a716-446655440000",
        "hubId": "550e8400-e29b-41d4-a716-446655440001"
      },
      "quantity": 10
    },
    {
      "stockId": {
        "productId": "550e8400-e29b-41d4-a716-446655440000",
        "hubId": "550e8400-e29b-41d4-a716-446655440001"
      },
      "quantity": 15
    }
  ]
}

### 2. 재고 준비 취소 요청
POST http://localhost:19001/api/v1/app/stock/abort
Content-Type: {{contentType}}

{
  "stocks": [
    {
      "stockId": {
        "productId": "550e8400-e29b-41d4-a716-446655440000",
        "hubId": "550e8400-e29b-41d4-a716-446655440001"
      },
      "quantity": 10
    },
    {
      "stockId": {
        "productId": "550e8400-e29b-41d4-a716-446655440000",
        "hubId": "550e8400-e29b-41d4-a716-446655440001"
      },
      "quantity": 5
    }
  ]
}

### 3. 상품의 소속 허브 조회
GET http://localhost:19001/api/v1/app/stock?{{productId}}
Content-Type: {{contentType}}


## 유저 서비스

### 1. 유저 정보 조회 (FeignClient UserClient.findByUserId)
GET http://localhost:19021/api/v1/app/users/{{user_id}}
Content-Type: {{contentType}}
Authorization: {{access_token}}
X-User-Id: {{user_id}}
X-User-Role: {{role}}


### 사용자 검증
POST {{host}}/api/v1/app/users/validate
Content-Type: {{contentType}}

{
  "username": "masteradmin",
  "password": "Password1!"
}
> {%
  if (response.body.userId) {
    client.global.set("user_id", response.body.userId.toString());
  } else {
    throw new Error("userId가 응답에 존재하지 않음");
  }
  client.global.set("username", response.body.username);
  client.global.set("role", response.body.role);
%}

### 로그인
POST {{host}}/api/v1/auth/login
Content-Type: {{contentType}}

{
  "username": "masteradmin",
  "password": "Password1!"
}
> {%
  let authHeader = response.headers.valueOf("Authorization");
  if (authHeader) {
    client.global.set("access_token", authHeader);
  }
%}
