### 환경 변수 설정
@host_prefix = http://localhost
@contentType = application/json

### 회원가입 (마스터 어드민)
POST {{host_prefix}}:19000/api/v1/users/signup
Content-Type: {{contentType}}

{
  "username": "test1",
  "slackEmail": "test1@email.com",
  "password": "Password1!",
  "role": "MASTER_ADMIN"
}

### 사용자 검증
POST {{host_prefix}}:19000/api/v1/app/users/validate
Content-Type: {{contentType}}

{
  "username": "test1",
  "password": "Password1!"
}
> {%
  if (response.body.userId) {
    client.global.set("user_id", response.body.userId.toString());
  } else {
    throw new Error("userId가 응답에 존재하지 않음");
  }
  client.global.set("username", response.body.username);
  client.global.set("role", response.body.role);
%}


### 로그인
POST {{host_prefix}}:19000/api/v1/auth/login
Content-Type: {{contentType}}

{
  "username": "test1",
  "password": "Password1!"
}
> {%
  let authHeader = response.headers.valueOf("Authorization");
  if (authHeader) {
    client.global.set("access_token", authHeader);
  }
%}

### 생산업체 허브 생성 요청 (허브 ID가 필요한 경우)
POST http://localhost:19000/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "서울특별시 센터",
  "locationApi": {
    "address": "서울특별시 송파구 송파대로 55",
    "latitude": 37.514219,
    "longitude": 127.112628
  }
}
> {%
  client.global.set("supplierHubId", response.body.hubId)
%}

### 수령업체 허브 생성 요청 (허브 ID가 필요한 경우)
POST http://localhost:19000/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "경기 남부 센터",
  "locationApi": {
    "address": "경기도 이천시 덕평로 257-21",
    "latitude": 37.210106,
    "longitude": 127.435027
  }
}
> {%
  client.global.set("customerHubId", response.body.hubId)
%}

### 생산업체 생성 요청
POST http://localhost:19000/api/v1/companies
Content-Type: {{contentType}}
Authorization: {{access_token}}

{
  "companyName": "신선한 식품",
  "companyType": "SUPPLIER",
  "hubId": "{{supplierHubId}}",
  "address": "서울특별시 강남구 테헤란로 123"
}
> {%
  client.global.set("supplierCompanyId", response.body.companyId)
%}

### 수령업체 생성 요청
POST http://localhost:19000/api/v1/companies
Content-Type: {{contentType}}
Authorization: {{access_token}}

{
  "companyName": "가구회사",
  "companyType": "CUSTOMER",
  "hubId": "{{customerHubId}}",
  "address": "서울특별시 서초구 서초대로 456"
}
> {%
  client.global.set("customerHubId", response.body.companyId)
%}

### 상품 생성 요청 (상품 ID가 필요한 경우)
POST http://localhost:19000/api/v1/products
Content-Type: {{contentType}}
Authorization: {{access_token}}

{
  "name": "유기농 바나나",
  "companyId": "{{supplierCompanyId}}",
  "hubId": "{{supplierHubId}}",
  "quantity": 10
}
> {%
  client.global.set("productId", response.body.productId)
%}

### 1. 주문 생성 요청
POST {{host_prefix}}:19000/api/v1/orders
Content-Type: {{contentType}}
Authorization: {{access_token}}}

{
  "supplierId": "{{supplierCompanyId}}",
  "companyId": "{{customerHubId}}",
  "customerId": 1,
  "orderItems": [
    {
      "productId": "{{productId}}",
      "quantity": 5
    }
  ],
  "deliveryAddress": "서울특별시 강남구 역삼동 123-45",
  "requestNotes": "문 앞에 놓아주세요."
}
> {%
  client.global.set("orderId", response.body.orderId)
%}

### 2. 주문 수정
PATCH {{host_prefix}}:19000/api/v1/orders/{orderId}
Content-Type: {{contentType}}
Authorization: {{access_token}}}

{
  "orderItems": [
    {
      "productId": "{{productId}}",
      "quantity": 10
    },
  ]
}


### 3. 주문 삭제
DELETE {{host_prefix}}:19000/api/v1/orders/{orderId}
Content-Type: {{contentType}}
Authorization: {{access_token}}}

### 4. 주문 조회 (기본 조회)
GET {{host_prefix}}:19000/api/v1/orders/search
Content-Type: {{contentType}}
Authorization: {{access_token}}}

### 5. 주문 검색 요청 (허브 ID로 필터링)
GET {{host_prefix}}/api/v1/orders/search?hubId={{hubId}}
Content-Type: {{contentType}}
Authorization: {{access_token}}}
