### 회원가입 (Signup)
POST http://localhost:19000/api/v1/users/signup
Content-Type: application/json

{
  "username": "test1",
  "slackEmail": "test1@email.com",
  "password": "Password1!",
  "role": "MASTER_ADMIN"
}

### 사용자 검증 (비밀번호 확인 및 userId, username, role 반환)
POST http://localhost:19000/api/v1/app/users/validate
Content-Type: application/json

{
  "username": "test1",
  "password": "Password1!"
}
> {%
  if (response.body.userId) {
    client.global.set("user_id", response.body.userId.toString());
  } else {
    throw new Error("userId가 응답에 존재하지 않음");
  }
  client.global.set("username", response.body.username);
  client.global.set("role", response.body.role);
%}

### 로그인 (JWT 발급)
POST http://localhost:19000/api/v1/auth/login
Content-Type: application/json

{
  "username": "test1",
  "password": "Password1!"
}
> {%
  let authHeader = response.headers.valueOf("Authorization");
  if (authHeader) {
    client.global.set("access_token", authHeader);
  } else {
    throw new Error("Authorization 헤더가 응답에 존재하지 않음");
  }
%}



###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "서울특별시 센터",
  "locationApi": {
    "address": "서울특별시 송파구 송파대로 55",
    "latitude": 37.514219,
    "longitude": 127.112628
  }
}

###
POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "경기 북부 센터",
  "locationApi": {
    "address": "경기도 고양시 덕양구 권율대로 570",
    "latitude": 37.649621,
    "longitude": 126.835836
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "경기 남부 센터",
  "locationApi": {
    "address": "경기도 이천시 덕평로 257-21",
    "latitude": 37.210106,
    "longitude": 127.435027
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "부산광역시 센터",
  "locationApi": {
    "address": "부산 동구 중앙대로 206",
    "latitude": 35.134183,
    "longitude": 129.056081
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "대구광역시 센터",
  "locationApi": {
    "address": "대구 북구 태평로 161",
    "latitude": 35.881539,
    "longitude": 128.581292
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "인천광역시 센터",
  "locationApi": {
    "address": "인천 남동구 정각로 29",
    "latitude": 37.447336,
    "longitude": 126.731539
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "광주광역시 센터",
  "locationApi": {
    "address": "광주 서구 내방로 111",
    "latitude": 35.153206,
    "longitude": 126.888950
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "대전광역시 센터",
  "locationApi": {
    "address": "대전 서구 둔산로 100",
    "latitude": 36.351524,
    "longitude": 127.378144
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "울산광역시 센터",
  "locationApi": {
    "address": "울산 남구 중앙로 201",
    "latitude": 35.543601,
    "longitude": 129.320901
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "세종특별자치시 센터",
  "locationApi": {
    "address": "세종특별자치시 한누리대로 2130",
    "latitude": 36.480838,
    "longitude": 127.289509
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "강원특별자치도 센터",
  "locationApi": {
    "address": "강원특별자치도 춘천시 중앙로 1",
    "latitude": 37.881221,
    "longitude": 127.729694
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "충청북도 센터",
  "locationApi": {
    "address": "충북 청주시 상당구 상당로 82",
    "latitude": 36.636993,
    "longitude": 127.489479
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "충청남도 센터",
  "locationApi": {
    "address": "충남 홍성군 홍북읍 충남대로 21",
    "latitude": 36.658826,
    "longitude": 126.660759
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "전북특별자치도 센터",
  "locationApi": {
    "address": "전북특별자치도 전주시 완산구 효자로 225",
    "latitude": 35.824193,
    "longitude": 127.114653
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "전라남도 센터",
  "locationApi": {
    "address": "전남 무안군 삼향읍 오룡길 1",
    "latitude": 34.813878,
    "longitude": 126.464678
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "경상북도 센터",
  "locationApi": {
    "address": "경북 안동시 풍천면 도청대로 455",
    "latitude": 36.574028,
    "longitude": 128.506568
  }
}

###

POST {{baseUrl}}/api/v1/hubs
Content-Type: application/json
Authorization: {{access_token}}

{
  "hubName": "경상남도 센터",
  "locationApi": {
    "address": "경남 창원시 의창구 중앙대로 300",
    "latitude": 35.241687,
    "longitude": 128.680407
  }
}
