###
GET {{baseUrl}}/api/v1/hubRoutes/{{hubRouteId}}
Authorization: {{access_token}}

###
PUT {{baseUrl}}/api/v1/hubRoutes/{{hubRouteId}}
Content-Type: application/json
Authorization: {{access_token}}

{
  "fromHubId": "",
  "toHubId": "",
  "distance": {},
  "duration": {}
}

###
DELETE {{baseUrl}}/api/v1/hubRoutes/{{hubRouteId}}
Authorization: {{access_token}}