management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  tracing:
    sampling:
      probability: 1.0

server:
  port: 19011

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    url: /springdoc/openapi3-order-service.json
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs-order-service
