### 로그인
### 회원가입 (Signup)
POST {{baseUrl}}/api/v1/users/signup
Content-Type: application/json

{
  "username": "master",
  "slackEmail": "master@email.com",
  "password": "Password1!",
  "role": "MASTER_ADMIN"
}

### 사용자 검증 (비밀번호 확인 및 userId, username, role 반환)
POST {{baseUrl}}/api/v1/app/users/validate
Content-Type: application/json

{
  "username": "master",
  "password": "Password1!"
}
> {%
  if (response.body.userId) {
    client.global.set("user_id", response.body.userId.toString());
  } else {
    throw new Error("userId가 응답에 존재하지 않음");
  }
  client.global.set("username", response.body.username);
  client.global.set("role", response.body.role);
%}

### 로그인 (JWT 발급)
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "master",
  "password": "Password1!"
}
> {%
  let authHeader = response.headers.valueOf("Authorization");
  if (authHeader) {
    client.global.set("access_token", authHeader);
  } else {
    throw new Error("Authorization 헤더가 응답에 존재하지 않음");
  }
%}

