### 로그인
### 회원가입 (Signup)
POST http://localhost:19000/api/v1/users/signup
Content-Type: application/json

{
  "username": "testuser6",
  "slackEmail": "testuser6@email.com",
  "password": "Password1!",
  "role": "HUB_MANAGER"
}

### 사용자 검증 (비밀번호 확인 및 userId, username, role 반환)
POST http://localhost:19000/api/v1/app/users/validate
Content-Type: application/json

{
  "username": "testuser6",
  "password": "Password1!"
}
> {%
  if (response.body.userId) {
    client.global.set("user_id", response.body.userId.toString());
  } else {
    throw new Error("userId가 응답에 존재하지 않음");
  }
  client.global.set("username", response.body.username);
  client.global.set("role", response.body.role);
%}

### 로그인 (JWT 발급)
POST http://localhost:19000/api/v1/auth/login
Content-Type: application/json

{
  "username": "testuser6",
  "password": "Password1!"
}
> {%
  let authHeader = response.headers.valueOf("Authorization");
  if (authHeader) {
    client.global.set("access_token", authHeader);
  } else {
    throw new Error("Authorization 헤더가 응답에 존재하지 않음");
  }
%}




### 내부에서 사용하는 엔드포인트
POST {{baseUrl}}/api/v1/app/slacks/message/1
Content-Type: application/json
Authorization: {{access_token}}

{
  "orderNumber": 1,
  "companyName": "해산물월드",
  "productInfo": "마른 오징어 50박스",
  "orderRequest": "12월 12일 3시까지는 보내주세요!",
  "fromHubName": "경기도 고양시 덕양구 권율대로 570",
  "stopoverHubNames": {
    "hubNames": ["대전 서구 둔산로 100", "부산 동구 중앙대로 206"]
  },
  "toHubName": "부산시 사하구 낙동대로 1번길 1 해산물월드",
  "deliveryUsers": {
    "deliveryUserNames": ["김말숙 / msk@seafood.world"]
  },
  "companyDeliveryUserName": "고길동 / kdk@sparta.world"
}
> {%
  client.global.set("slackId", response.body.slackId)
%}

###
POST {{baseUrl}}/api/v1/app/slacks/message/users/1
Content-Type: application/json
Authorization: {{access_token}}

{
  "postContentsRequest": {
    "message": "유저 채널에 발송되는 슬랙 메시지 입니다."
  }
}
> {%
  client.global.set("slackId", response.body.slackId)
%}

###
POST {{baseUrl}}/api/v1/app/slacks/message/users/1
Content-Type: application/json
Authorization: {{access_token}}

{
  "postContentsRequest": {
    "message": "서킷 브레이커"
  }
}
> {%
  client.global.set("slackId", response.body.slackId)
%}


###
GET {{baseUrl}}/api/v1/slacks/{{slackId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IkhVQl9NQU5BR0VSIiwiaWF0IjoxNzQyNjc3Njg0LCJleHAiOjE3NDI2ODEyODR9.7UJlCM3grooUAXTz6dFyOdFo-_l881GmMsWV_xOb35w

###
PATCH {{baseUrl}}/api/v1/slacks/{{slackId}}
Content-Type: application/json

{
  "userId": 1,
  "patchContentsRequest": {
    "message": "수정된 메시지 내용"
  }
}

###
DELETE {{baseUrl}}/api/v1/slacks/{{slackId}}

###
GET {{baseUrl}}/api/v1/slacks/search?message=주문&isAsc=true&sortBy=createdAt&page=0&size=10






###
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=AIzaSyC1j0Qm-sEsCj4KykvhNEGgDWo3pg7dS64
content-Type: application/json

{
  "contents": [{
    "parts": [{
      "text": "주문 번호: 1\n주문자 정보: 해산물월드\n상품 정보: 마른 오징어 50박스\n요청 사항: 12월 12일 3시까지는 보내주세요!\n발송지: 경기도 고양시 덕양구 권율대로 570\n경유지: 대전 서구 둔산로 100, 부산 동구 중앙대로 206\n도착지: 부산시 사하구 낙동대로 1번길 1 해산물월드\n배송 담당자: 김말숙 / msk@seafood.world 으로 요청사항 시간에 도착하려면 언제 출발해야 하는지 알려줘"
    }]
  }]
}
