
### 재고 생성 API (PostStockRequestDto 사용)
POST {{baseUrl}}/api/v1/app/stock
Content-Type: application/json
Authorization: {{access_token}}

{
    "stockId": {
        "productId": "{{productId}}",
        "hubId": "{{hubId}}"
    },
    "quantity": 100
}

### 재고 생성 API2 (PostStockRequestDto 사용)
POST {{baseUrl}}/api/v1/app/stock
Content-Type: application/json
Authorization: {{access_token}}

{
    "stockId": {
        "productId": "{{productId}}",
        "hubId": "{{hubId}}"
    },
    "quantity": 500
}

### 상품 ID 로 가장 재고 많은 결과 얻어오기 (하나만)
GET {{baseUrl}}/api/v1/app/stock?productId={{productId}}
Authorization: {{access_token}}

### 재고 준비 (여러 상품 일괄)
POST {{baseUrl}}/api/v1/app/stock/prepare
Content-Type: application/json
Authorization: {{access_token}}

{
  "stocks": [
    {
      "stockId": {
        "productId": "{{productId}}",
        "hubId": "{{hubId}}"
      },
      "quantity": 10
    },
    {
      "stockId": {
        "productId": "{{productId}}",
        "hubId": "{{hubId}}"
      },
      "quantity": 15
    }
  ]
}


### 재고 준비 취소
POST {{baseUrl}}/api/v1/app/stock/abort
Content-Type: application/json
Authorization: {{access_token}}

{
  "stocks": [
    {
      "stockId": {
        "productId": "{{productId}}",
        "hubId": "{{hubId}}"
      },
      "quantity": 10
    },
    {
      "stockId": {
        "productId": "{{productId}}",
        "hubId": "{{hubId}}"
      },
      "quantity": 5
    }
  ]
}


### 상품별 재고 삭제
DELETE {{baseUrl}}/api/v1/app/stock/all-by-product?productId={{productId}}
Authorization: {{access_token}}

### 창고별 재고 삭제
DELETE {{baseUrl}}/api/v1/app/stock/all-by-hub?hubId={{hubId}}
Authorization: {{access_token}}